apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  revision: llm-d-gateway
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
