apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-lint-task
spec:
  podTemplate:
    imagePullSecrets:
      - name: icr-secret
  workspaces:
    - name: source
  steps:
    - name: run-lint
      image: us.icr.io/ibm-hc4ai-operator/golangci-lint:v2.0.3
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/bash
        set -e

        echo "Running golangci-lint..."
        cd $(workspaces.source.path)

        echo "🔐 Extracting Git credentials from workspace..."
        GIT_USER=$(cat /workspace/git-auth/username)
        GIT_TOKEN=$(cat /workspace/git-auth/token)

        if [ -z "$GIT_USER" ] || [ -z "$GIT_TOKEN" ]; then
          echo "❌ Error: Missing git-auth credentials"
          exit 1
        fi

        echo "🔐 Configuring Git..."
        git config --global user.email "ci-tag-bot@example.com"
        git config --global user.name "ci-tag-bot"
        git config --global url."https://${GIT_USER}:${GIT_TOKEN}@github.com".insteadOf "https://github.com"
        git config --global --add safe.directory "$(pwd)"
        
        # Verify config file exists
        if [ -f .golangci.yml ] || [ -f .golangci.yaml ] || [ -f .golangci.toml ]; then
          echo "✅ Found golangci-lint config file"
        else
          echo "⚠️ No golangci-lint config file found. Using default linters"
        fi

        # Run lint
        make lint
