apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-test-task
spec:
  workspaces:
    - name: source
  steps:
    - name: install-deps
      image: quay.io/projectquay/golang:1.24
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/bash
        echo "Installing Ginkgo..."
        go install github.com/onsi/ginkgo/ginkgo@latest
        export PATH=$PATH:$(go env GOPATH)/bin
        echo "Ginkgo installed:"
        ginkgo version
        cd $(workspaces.source.path)
        echo "Running tests with Ginkgo..."
        
        echo "🔐 Extracting Git credentials from workspace..."
        GIT_USER=$(cat /workspace/git-auth/username)
        GIT_TOKEN=$(cat /workspace/git-auth/token)

        if [ -z "$GIT_USER" ] || [ -z "$GIT_TOKEN" ]; then
          echo "❌ Error: Missing git-auth credentials"
          exit 1
        fi

        echo "🔐 Configuring Git..."
        git config --global user.email "ci-tag-bot@example.com"
        git config --global user.name "ci-tag-bot"
        git config --global url."https://${GIT_USER}:${GIT_TOKEN}@github.com".insteadOf "https://github.com"
        git config --global --add safe.directory "$(pwd)"
        
        # required for go build with tokenizer lib linking
        dnf install -y gcc-c++ libstdc++ libstdc++-devel && dnf clean all
        
        go env -w GOFLAGS=-buildvcs=false
        make test
