apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-test-task
spec:
  workspaces:
    - name: source
    - name: registry
  steps:
    - name: install-deps
      image: quay.io/projectquay/golang:1.24
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      script: |
        #!/bin/bash
        set -euox pipefail

        echo "Installing Ginkgo..."
        go install github.com/onsi/ginkgo/ginkgo@latest
        export PATH=$PATH:$(go env GOPATH)/bin
        echo "Ginkgo installed:"
        ginkgo version
        cd $(workspaces.source.path)
        echo "Running tests with Ginkgo..."

        echo "🔐 Extracting Git credentials from workspace..."
        GIT_USER=$(cat /workspace/git-auth/username)
        GIT_TOKEN=$(cat /workspace/git-auth/token)
        export GIT_NM_USER=${GIT_USER}
        export NM_TOKEN=${GIT_TOKEN}

        if [ -z "$GIT_USER" ] || [ -z "$GIT_TOKEN" ]; then
          echo "❌ Error: Missing git-auth credentials"
          exit 1
        fi

        echo "🔐 Configuring Git..."
        git config --global user.email "ci-tag-bot@example.com"
        git config --global user.name "ci-tag-bot"
        git config --global url."https://${GIT_USER}:${GIT_TOKEN}@github.com".insteadOf "https://github.com"
        git config --global --add safe.directory "$(pwd)"

        echo "Installing requirements"
        dnf install -y gettext ca-certificates gcc-c++ libstdc++ libstdc++-devel jq podman-docker && dnf clean all
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl $(go env GOBIN)
        go install sigs.k8s.io/kustomize/kustomize/v5@v5.6.0

        echo "Running unit tests"
        go env -w GOFLAGS=-buildvcs=false
        make test-unit

        echo "🔐 Extracting Quay Credentials..."
        mkdir -p /root/.docker
        cp /workspace/registry/.dockerconfigjson /root/.docker/config.json
        QUAY_USERNAME=$(jq -r '.auths["quay.io"].username' /root/.docker/config.json)
        QUAY_PASSWORD=$(jq -r '.auths["quay.io"].password' /root/.docker/config.json)
        if [ "$QUAY_USERNAME" = "null" ] || [ "$QUAY_PASSWORD" = "null" ]; then
          echo "❌ Error: Missing registry credentials"
          exit 1
        fi

        echo "Pulling the vllm simulator image"
        podman login quay.io --username ${QUAY_USERNAME} --password ${QUAY_PASSWORD}
        podman pull quay.io/llm-d/vllm-sim:0.0.4

        echo "Setting up a Kind cluster for integration tests"
        export CONTAINER_TOOL=podman
        export CONTAINER_RUNTIME=${CONTAINER_TOOL}
        export KIND_CLUSTER_NAME="ci-integration-tests"
        go install sigs.k8s.io/kind@v0.27.0
        make env-dev-kind DEV_VERSION="$(git rev-parse HEAD)"
        export KUBECONFIG="/tmp/kubeconfig-${KIND_CLUSTER_NAME}"
        kind --name ${KIND_CLUSTER_NAME} export kubeconfig --kubeconfig ${KUBECONFIG}

        echo "Running integration tests"
        make test-integration
